### ISSUE TITLE
Highlight color of keywords?

### ISSUE THREAD

**Issue by jradavenport** [weaverba137/language-idl#2]
An example of this from IDLWAVE in Emacs:
<img width="192" alt="screen shot 2015-11-16 at 3 17 36 pm" src="https://cloud.githubusercontent.com/assets/3179868/11197869/3a7978f4-8c75-11e5-98d1-36c020b58159.png">

Briefly looking thru idl.json, I'm not sure how to capture this pattern

**Comment by weaverba137** [comment]
Interesting suggestion, I think I can figure out a regular expression that would capture that.

**Comment by jradavenport** [comment]
Upgraded to v0.3.0 from within Atom. This is current behavior for Syntax Theme = Atom Light:
<img width="397" alt="screen shot 2015-11-18 at 11 59 13 am" src="https://cloud.githubusercontent.com/assets/3179868/11252606/f01e1c60-8deb-11e5-834f-5e63ef4bba76.png">

And for GitHub 2014
<img width="381" alt="screen shot 2015-11-18 at 11 59 41 am" src="https://cloud.githubusercontent.com/assets/3179868/11252625/00d1c020-8dec-11e5-951f-a555392d4d79.png">

So nothing bad, but interesting!

Thanks for being willing to fix this, and for maintaining this for Atom!!!!

**Comment by weaverba137** [comment]
Yes, the `/` is treated as an assignment operator, which in some sense, it really is.
