### ISSUE TITLE
How to install language-idl in Atom 1.16.0

### ISSUE THREAD

**Issue by Csega** [weaverba137/language-idl#5]
Hi Guys!

I tried to install this extension from Atom package repository, but I cannot find it. I tried to search for language-idl and interactive data languate. Could you help me with the installation? I use Atom 1.16.0.

Thanks for your help!

**Comment by weaverba137** [comment]
It is listed in the package index:  https://atom.io/packages/search?q=language-idl

What *exact* error messages do you get when you try to install it?

**Comment by Csega** [comment]
There was no error message, I just couldn't find it by simply typing the name. However, it turned out, that I was looking for it in the Packages section in the Settings menu, but in the end, I found it at the +Install section. Thanks for your quick answer!

**Comment by weaverba137** [comment]
Ah, right.  I've tripped over that Packages versus Install thing myself.
